#!/usr/bin/env bash

# set this to your active development branch
develop_branch="develop"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

# only check commit messages on main development branch
[ "$current_branch" == "$develop_branch" ] && exit 0

# regex to validate in commit msg
# Accepted format: <jira-issue-id> <TYPE> (<Scope>) <Brief description>
# E.g. BAU-3632 FEAT (Whisky map) Add new distilleries
commit_regex='((merge\sbranch)|(([A-Z]+-[0-9]+|NON-JIRA)\s(BREAK|DOCS|FEAT|FIX|FORMAT|MAINT|MERGE|TEST)\s\(.+\)\s.+))'
error_msg="Aborting commit. Your commit message does not meet VisitScotland's commit message standards."

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi