export { default as SiteSearchToggleButton } from '../../components/patterns/site-search/components/SiteSearchToggleButton.vue'
export { default as SkipToButton } from '../../components/patterns/skip-to/components/SkipToButton.vue'
export { default as Address } from '../../components/elements/address/Address.vue'
export { default as Button } from '../../components/elements/button/Button.vue'
export { default as FormInput } from '../../components/elements/form-input/FormInput.vue'
export { default as Heading } from '../../components/elements/heading/Heading.vue'
export { default as Icon } from '../../components/elements/icon/Icon.vue'
export { default as Img } from '../../components/elements/img/Img.vue'
export { default as Col } from '../../components/elements/layout/Col.vue'
export { default as Container } from '../../components/elements/layout/Container.vue'
export { default as Row } from '../../components/elements/layout/Row.vue'
export { default as Link } from '../../components/elements/link/Link.vue'
export { default as List } from '../../components/elements/list/List.vue'
export { default as Modal } from '../../components/elements/modal/Modal.vue'
export { default as Panel } from '../../components/elements/panel/Panel.vue'
export { default as Prototype } from '../../components/elements/prototype/Prototype.vue'
export { default as PsrEmbed } from '../../components/elements/psr-embed/PsrEmbed.vue'
export { default as RichTextWrapper } from '../../components/elements/rich-text-wrapper/RichTextWrapper.vue'
export { default as Svg } from '../../components/elements/svg/Svg.vue'
export { default as Tag } from '../../components/elements/tag/Tag.vue'
export { default as Tooltip } from '../../components/elements/tooltip/Tooltip.vue'
export { default as Video } from '../../components/elements/video/Video.vue'
export { default as Accordion } from '../../components/patterns/accordion/Accordion.vue'
export { default as ComponentsAccordionItem } from '../../components/patterns/accordion/components/AccordionItem.vue'
export { default as ComponentsAccordionToggle } from '../../components/patterns/accordion/components/AccordionToggle.vue'
export { default as Article } from '../../components/patterns/article/Article.vue'
export { default as ComponentsArticleSection } from '../../components/patterns/article/components/ArticleSection.vue'
export { default as ComponentsArticleSidebar } from '../../components/patterns/article/components/ArticleSidebar.vue'
export { default as Banner } from '../../components/patterns/banner/Banner.vue'
export { default as Breadcrumb } from '../../components/patterns/breadcrumb/Breadcrumb.vue'
export { default as ComponentsBreadcrumbItem } from '../../components/patterns/breadcrumb/components/BreadcrumbItem.vue'
export { default as CannedSearch } from '../../components/patterns/canned-search/CannedSearch.vue'
export { default as ComponentsCannedSearchBadges } from '../../components/patterns/canned-search/components/CannedSearchBadges.vue'
export { default as ComponentsCannedSearchCategories } from '../../components/patterns/canned-search/components/CannedSearchCategories.vue'
export { default as ComponentsCannedSearchCuisines } from '../../components/patterns/canned-search/components/CannedSearchCuisines.vue'
export { default as ComponentsCannedSearchDates } from '../../components/patterns/canned-search/components/CannedSearchDates.vue'
export { default as ComponentsCannedSearchDuration } from '../../components/patterns/canned-search/components/CannedSearchDuration.vue'
export { default as ComponentsCannedSearchLogos } from '../../components/patterns/canned-search/components/CannedSearchLogos.vue'
export { default as ComponentsCannedSearchPrice } from '../../components/patterns/canned-search/components/CannedSearchPrice.vue'
export { default as ComponentsCannedSearchProductCard } from '../../components/patterns/canned-search/components/CannedSearchProductCard.vue'
export { default as ComponentsCannedSearchStars } from '../../components/patterns/canned-search/components/CannedSearchStars.vue'
export { default as ComponentsCannedSearchSubHeading } from '../../components/patterns/canned-search/components/CannedSearchSubHeading.vue'
export { default as ComponentsCannedSearchSummaryBox } from '../../components/patterns/canned-search/components/CannedSearchSummaryBox.vue'
export { default as ComponentsCannedSearchTourDeparts } from '../../components/patterns/canned-search/components/CannedSearchTourDeparts.vue'
export { default as ComponentsCannedSearchTourRuns } from '../../components/patterns/canned-search/components/CannedSearchTourRuns.vue'
export { default as Caption } from '../../components/patterns/caption/Caption.vue'
export { default as ComponentsCaptionImageMap } from '../../components/patterns/caption/components/CaptionImageMap.vue'
export { default as Carousel } from '../../components/patterns/carousel/Carousel.vue'
export { default as ComponentsCarouselSlide } from '../../components/patterns/carousel/components/CarouselSlide.vue'
export { default as DescriptionList } from '../../components/patterns/description-list/DescriptionList.vue'
export { default as ComponentsDescriptionListDetail } from '../../components/patterns/description-list/components/DescriptionListDetail.vue'
export { default as ComponentsDescriptionListItem } from '../../components/patterns/description-list/components/DescriptionListItem.vue'
export { default as ComponentsDescriptionListTerm } from '../../components/patterns/description-list/components/DescriptionListTerm.vue'
export { default as Dropdown } from '../../components/patterns/dropdown/Dropdown.vue'
export { default as ComponentsDropdownItem } from '../../components/patterns/dropdown/components/DropdownItem.vue'
export { default as EmbedWrapper } from '../../components/patterns/embed-wrapper/EmbedWrapper.vue'
export { default as FavouritesList } from '../../components/patterns/favourites/FavouritesList.vue'
export { default as FavouritesStore } from '../../components/patterns/favourites/favourites.store.js'
export { default as ComponentsFavouritesListToggleButton } from '../../components/patterns/favourites/components/FavouritesListToggleButton.vue'
export { default as ComponentsFavouritesListViewButton } from '../../components/patterns/favourites/components/FavouritesListViewButton.vue'
export { default as Footer } from '../../components/patterns/footer/Footer.vue'
export { default as ExamplesFooterExample } from '../../components/patterns/footer/__examples__/footer.example.vue'
export { default as ComponentsFooterAccordionItem } from '../../components/patterns/footer/components/FooterAccordionItem.vue'
export { default as ComponentsFooterCopyright } from '../../components/patterns/footer/components/FooterCopyright.vue'
export { default as ComponentsFooterNavList } from '../../components/patterns/footer/components/FooterNavList.vue'
export { default as ComponentsFooterNavListItem } from '../../components/patterns/footer/components/FooterNavListItem.vue'
export { default as ComponentsFooterSocialItem } from '../../components/patterns/footer/components/FooterSocialItem.vue'
export { default as ComponentsFooterSocialMenu } from '../../components/patterns/footer/components/FooterSocialMenu.vue'
export { default as ComponentsFooterUtilityList } from '../../components/patterns/footer/components/FooterUtilityList.vue'
export { default as Form } from '../../components/patterns/form/Form.vue'
export { default as GlobalMenu } from '../../components/patterns/global-menu/GlobalMenu.vue'
export { default as ComponentsGlobalMenuDropdown } from '../../components/patterns/global-menu/components/GlobalMenuDropdown.vue'
export { default as ComponentsGlobalMenuLanguage } from '../../components/patterns/global-menu/components/GlobalMenuLanguage.vue'
export { default as ComponentsGlobalMenuLanguageItem } from '../../components/patterns/global-menu/components/GlobalMenuLanguageItem.vue'
export { default as ComponentsGlobalMenuList } from '../../components/patterns/global-menu/components/GlobalMenuList.vue'
export { default as Icentre } from '../../components/patterns/icentre/Icentre.vue'
export { default as IconList } from '../../components/patterns/icon-list/IconList.vue'
export { default as ComponentsIconListItem } from '../../components/patterns/icon-list/components/IconListItem.vue'
export { default as ImageWithCaption } from '../../components/patterns/image-with-caption/ImageWithCaption.vue'
export { default as Itinerary } from '../../components/patterns/itineraries/Itinerary.vue'
export { default as ItinerariesStore } from '../../components/patterns/itineraries/itineraries.store.js'
export { default as ComponentsItineraryBorderOverlapWrapper } from '../../components/patterns/itineraries/components/ItineraryBorderOverlapWrapper.vue'
export { default as ComponentsItineraryDay } from '../../components/patterns/itineraries/components/ItineraryDay.vue'
export { default as ComponentsItineraryStop } from '../../components/patterns/itineraries/components/ItineraryStop.vue'
export { default as ComponentsItineraryStopInfo } from '../../components/patterns/itineraries/components/ItineraryStopInfo.vue'
export { default as ComponentsItineraryTips } from '../../components/patterns/itineraries/components/ItineraryTips.vue'
export { default as ComponentsItineraryMap } from '../../components/patterns/itineraries/components/itinerary-map/ItineraryMap.vue'
export { default as ComponentsItineraryMapMarker } from '../../components/patterns/itineraries/components/itinerary-map/components/ItineraryMapMarker.vue'
export { default as LinkList } from '../../components/patterns/link-list/LinkList.vue'
export { default as ComponentsLinkListItem } from '../../components/patterns/link-list/components/LinkListItem.vue'
export { default as ListicleItem } from '../../components/patterns/listicle/ListicleItem.vue'
export { default as MegaNav } from '../../components/patterns/mega-nav/MegaNav.vue'
export { default as ExamplesMeganavExample } from '../../components/patterns/mega-nav/__examples__/meganav.example.vue'
export { default as ComponentsMegaNavAccordionItem } from '../../components/patterns/mega-nav/components/MegaNavAccordionItem.vue'
export { default as ComponentsMegaNavDropdown } from '../../components/patterns/mega-nav/components/MegaNavDropdown.vue'
export { default as ComponentsMegaNavFeaturedItem } from '../../components/patterns/mega-nav/components/MegaNavFeaturedItem.vue'
export { default as ComponentsMegaNavList } from '../../components/patterns/mega-nav/components/MegaNavList.vue'
export { default as ComponentsMegaNavListItem } from '../../components/patterns/mega-nav/components/MegaNavListItem.vue'
export { default as ComponentsMegaNavTopMenu } from '../../components/patterns/mega-nav/components/MegaNavTopMenu.vue'
export { default as ComponentsMegaNavTopMenuItem } from '../../components/patterns/mega-nav/components/MegaNavTopMenuItem.vue'
export { default as Megalinks } from '../../components/patterns/megalinks/Megalinks.vue'
export { default as ComponentsMegalinkLinkList } from '../../components/patterns/megalinks/components/megalink-link-list/MegalinkLinkList.vue'
export { default as ComponentsMegalinkMultiImage } from '../../components/patterns/megalinks/components/megalink-multi-image/MegalinkMultiImage.vue'
export { default as ComponentsMegalinkSingleImage } from '../../components/patterns/megalinks/components/megalink-single-image/MegalinkSingleImage.vue'
export { default as ModuleWrapper } from '../../components/patterns/module-wrapper/ModuleWrapper.vue'
export { default as PageIntro } from '../../components/patterns/page-intro/PageIntro.vue'
export { default as PsrModule } from '../../components/patterns/psr-module/PsrModule.vue'
export { default as Quote } from '../../components/patterns/quote/Quote.vue'
export { default as SiteSearch } from '../../components/patterns/site-search/SiteSearch.vue'
export { default as SkipTo } from '../../components/patterns/skip-to/SkipTo.vue'
export { default as SocialCreditLink } from '../../components/patterns/social-credit-link/SocialCreditLink.vue'
export { default as SocialShare } from '../../components/patterns/social-share/SocialShare.vue'
export { default as ComponentsSocialShareItem } from '../../components/patterns/social-share/components/SocialShareItem.vue'
export { default as StretchedLinkCard } from '../../components/patterns/stretched-link-card/StretchedLinkCard.vue'
export { default as ComponentsStretchedLinkPanels } from '../../components/patterns/stretched-link-card/components/StretchedLinkPanels.vue'
export { default as SummaryBoxList } from '../../components/patterns/summary-box/SummaryBoxList.vue'
export { default as ComponentsSummaryBoxDistanceListItem } from '../../components/patterns/summary-box/components/SummaryBoxDistanceListItem.vue'
export { default as ComponentsSummaryBoxListItem } from '../../components/patterns/summary-box/components/SummaryBoxListItem.vue'
export { default as Tabs } from '../../components/patterns/tabs/Tabs.vue'
export { default as ComponentsTabItem } from '../../components/patterns/tabs/components/TabItem.vue'
export { default as ToggleButton } from '../../components/patterns/toggle-button/ToggleButton.vue'
export { default as VideoCaption } from '../../components/patterns/video-caption/VideoCaption.vue'
export { default as DSHeader } from '../../components/DSHeader.vue'
export { default as DSSidebar } from '../../components/DSSidebar.vue'
export { default as BaseHeader } from '../../components/base/Header.vue'
export { default as BaseSidebar } from '../../components/base/Sidebar.vue'
export { default as TemplatesExample } from '../../components/templates/Example.vue'
export { default as ElementsCheckbox } from '../../components/elements/checkbox/Checkbox.vue'
export { default as ElementsInput } from '../../components/elements/input/Input.vue'
export { default as ElementsRecaptcha } from '../../components/elements/recaptcha/Recaptcha.vue'
export { default as ElementsSelect } from '../../components/elements/select/Select.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
