import { resolve } from 'path'

export default {
    //...
    components: {
        dirs: [
            '~/utils',
            '~/components',
            '~/components/elements/',
            '~/components/patterns',
            '~/components/elements/address',
            '~/components/elements/button',
            '~/components/elements/form-input',
            '~/components/elements/heading',
            '~/components/elements/icon',
            '~/components/elements/img',
            '~/components/elements/layout',
            '~/components/elements/link',
            '~/components/elements/list',
            '~/components/elements/modal',
            '~/components/elements/panel',
            '~/components/elements/prototype',
            '~/components/elements/psr-embed',
            '~/components/elements/rich-text-wrapper',
            '~/components/elements/svg',
            '~/components/elements/svg-link',
            '~/components/elements/tag',
            '~/components/elements/tooltip',
            '~/components/elements/video',
            '~/components/patterns/accordion',
            '~/components/patterns/accordion/components',
            '~/components/patterns/article',
            '~/components/patterns/banner',
            '~/components/patterns/breadcrumb',
            '~/components/patterns/canned-search',
            '~/components/patterns/caption',
            '~/components/patterns/carousel',
            '~/components/patterns/description-list',
            '~/components/patterns/dropdown',
            '~/components/patterns/embed-wrapper',
            '~/components/patterns/favourites',
            '~/components/patterns/footer',
            '~/components/patterns/form',
            '~/components/patterns/global-menu',
            '~/components/patterns/icentre',
            '~/components/patterns/icon-list',
            '~/components/patterns/image-with-caption',
            '~/components/patterns/itineraries',
            '~/components/patterns/link-list',
            '~/components/patterns/listicle',
            '~/components/patterns/mega-nav',
            '~/components/patterns/megalinks',
            '~/components/patterns/module-wrapper',
            '~/components/patterns/page-intro',
            '~/components/patterns/psr-module',
            '~/components/patterns/quote',
            '~/components/patterns/site-search',
            '~/components/patterns/skip-to',
            '~/components/patterns/social-credit-link',
            '~/components/patterns/social-share',
            '~/components/patterns/stretched-link-card',
            '~/components/patterns/summary-box',
            '~/components/patterns/tabs',
            '~/components/patterns/toggle-button',
            '~/components/patterns/video-caption',
            '~/components/patterns/canned-search',
            '~/components/patterns/video-caption',
        ]
    },
    modules: [
        '@nuxtjs/style-resources',
        '@nuxt/content'
    ],
    styleResources: {
        scss: ['~assets/styles/core.styles.scss']
    },
    content: {
        // Options
    }
}