target:
  url: "http://localhost:8080"
backend:
  url: "http://localhost:8080"

filters:
  userAgent:
    defaultPolicy: whitelist
  paths:
    defaultPolicy: blacklist
    exceptions:
      exact:
        - /site/demo
cache:
  type: none

debug: true
