/content/documents/www.visitscotland.com-it/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 34c2d00b-c612-4545-8438-728fc1c25714
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: it
