definitions:
  config:
    /hippo:namespaces/visitscotland/ProductSearchLink:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: db2d408f-4535-4bd1-b0ae-c21f39a51107
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: a56809be-6350-495d-94ef-ce60b3c66cd4
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: de8d6804-0895-4f97-94b0-ced5a3c8dbac
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.visitscotland.com/visitscotland/nt/1.0
          /search:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:search
            hipposysedit:primary: false
            hipposysedit:type: visitscotland:ProductsSearch
          /label:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: visitscotland:label
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required, 'visitscotland:short-string-validator']
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: visitscotland:ProductSearchLink
          visitscotland:label: ''
          /visitscotland:search:
            jcr:primaryType: visitscotland:ProductsSearch
            visitscotland:dmsAwards: []
            visitscotland:dmsCategories: []
            visitscotland:dmsFacilities: []
            visitscotland:location: ''
            visitscotland:producttype: ''
            visitscotland:officialrating: []
            visitscotland:productType: ''
            visitscotland:distance: 10.0
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /search:
            jcr:primaryType: frontend:plugin
            caption: ProductsSearch
            field: search
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            hint: ''
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /label:
            jcr:primaryType: frontend:plugin
            caption: CTA text
            field: label
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: ''
