/content/documents/www.visitscotland.com-de/site:
  .meta:order-before: shared
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 566ee841-076e-4d28-86bf-782ec8b201f2
  hippostd:foldertype: [new-translated-folder, new-page, new-module]
  hippotranslation:id: a65bff6c-4edf-4d28-b036-84bdee4b4bcd
  hippotranslation:locale: de
