version: "3"
services:
  headless:
    image: rendora/chrome-headless:latest
    network_mode: "host"
    tmpfs:
      - /tmp
  rendora:
    image: rendora/rendora
    network_mode: "host"
    volumes:
      - ./config.yaml:/etc/rendora/config.yaml
