name: Build Design System

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["feature/*"]
  # # Runs on pushes targeting the default branch
  # pull_request_target:
  #   types:
  #     - opened
  #     - edited
  #     - synchronize
  #     - reopened
  # Allows this workflow to be called from other workflows
  workflow_call:
    secrets:
      VS_ENV_FILE:
        description: 'A token passed from the caller workflow'
        required: true
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup Yarn'
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 18.14.2
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: 'Create .env file'
        run: |
          echo "${{ secrets.VS_ENV_FILE }}" > .env
      - name: 'Build system files'
        run: |
          cd ../
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn system:build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@master
        with:
          name: github-pages
          path: ./dist/system