name: Cleanup S3
on:
  pull_request:
    types:
      - closed

jobs:
  auth:
    uses: visitscotland/design-system/.github/workflows/setup-aws-credentials.yml
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Generate bucket name from PR branch name
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          echo "BUCKET_NAME=${GIT_BRANCH////-}-${GIT_HASH}-sutvs" >> $GITHUB_ENV
      - run: |
          aws s3api delete-bucket --bucket ${{env.BUCKET_NAME}}