name: Create S3 bucket for SUT environments

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

env:
  AWS_REGION: 'eu-west-2'

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: 'eu-west-2'
          role-duration-seconds: 1200

      - name: Establish bucket name
        run: |
          echo "BUCKET_NAME=visitscotland-sut" >> $GITHUB_ENV

      - name: Check if bucket already exists
        id: check-bucket
        run: |
          aws s3api head-bucket --bucket ${{ env.BUCKET_NAME }} 2>/dev/null && echo "BUCKET_EXISTS=true" >> $GITHUB_ENV || echo "BUCKET_EXISTS=false" >> $GITHUB_ENV
          echo ${{ env.BUCKET_EXISTS }}
          echo "Test"
          echo ${{ env.BUCKET_EXISTS != true }}

      - name: Creating new S3 bucket
        if: ${{ env.BUCKET_EXISTS != true }}
        run: |
          commit_hash=`git rev-parse HEAD`
          aws s3api create-bucket --bucket ${{env.BUCKET_NAME}} --create-bucket-configuration LocationConstraint=eu-west-2
          aws s3api put-public-access-block --bucket ${{env.BUCKET_NAME}} --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"
          aws s3api put-bucket-policy --bucket ${{env.BUCKET_NAME}} --policy "{
            \"Version\": \"2012-10-17\",
            \"Statement\": [
                {
                    \"Sid\": \"PublicReadGetObject\",
                    \"Effect\": \"Allow\",
                    \"Principal\": \"*\",
                    \"Action\": \"s3:GetObject\",
                    \"Resource\": \"arn:aws:s3:::${{env.BUCKET_NAME}}/*\"
                }
            ]
          }"
          aws s3 website s3://${{ env.BUCKET_NAME }} --index-document index.html
    
