name: Create SUT Environment

# This Workflow creates a System Under Test Environment for feature branches
# It uses an AWS S3 bucket to host the static files

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab in the GitHub dashboard
  workflow_dispatch: {}

jobs:
    # Reuse the build workflow to avoid repetition
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Create a GitHub environment for the static hosting (to expose the S3 URL)
    environment:
      name: ds-s3-deployment
      url: ${{ env.S3_URL }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_DEV_ACCOUNT_ID }}:role/GitHubOIDC
          aws-region: eu-west-2
      - name: Set bucket name
        run: |
          echo "BUCKET_NAME=dev-visitscotland-sut" >> $GITHUB_ENV

      - name: Download GitHub artifact
        uses: actions/download-artifact@v3
        with:
          name: ds-build
          path: ./dist/system
          
      - name: Generate folder name from PR reference
        run: |
          PR_REF=${{ github.ref_name }}
          echo "FOLDER_NAME=${PR_REF////-}-sutvs" >> $GITHUB_ENV

      - name: Synchronizing to S3
        id: aws-sync
        run: |
          echo "Deploying to https://${{ env.BUCKET_NAME }}.s3.eu-west-2.amazonaws.com"
          aws s3 sync ./dist/system/ s3://${{env.BUCKET_NAME}}/${{env.FOLDER_NAME}}
          echo "S3_URL=https://${{env.BUCKET_NAME}}.s3.eu-west-2.amazonaws.com/${{env.FOLDER_NAME}}/index.html" >> $GITHUB_ENV

