name: s3-deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["feature/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: 'Create env file'
        run: |
          echo "${{ secrets.VS_ENV_FILE }}" > .env
      - run: |
          yarn system:build
  aws-s3-deploy:
    runs-on: ubuntu-latest
    needs: build
    # Create an environment for the static hosting enabled & Pulumi created S3 Bucket
    environment:
      name: ds-s3-deployment
      url: ${{ steps.aws-sync.outputs.s3_url }}
    steps:
      - name: Get branch name for bucket name
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=${GIT_BRANCH////-}" >> $GITHUB_ENV
      - name: Create bucket in S3
        uses: aitorres/aws-s3-create-bucket@v1.2.0
        with:
          bucket-name: ${{ env.GIT_BRANCH }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-2'
          acl: 'public-read'
      - name: Sync with AWS s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.GIT_BRANCH }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'   # optional: defaults to us-east-1
          SOURCE_DIR: './dist/system'      # optional: defaults to entire repository
