name: S3 Build and Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["feature/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

env:
  applicationfolder: dist/system
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'eu-west-2'

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: 'Create env file'
        run: |
          echo "${{ secrets.VS_ENV_FILE }}" > .env
      - run: |
          yarn system:build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Create an environment for the static hosting
    environment:
      name: ds-s3-deployment
      url: ${{ steps.aws-sync.outputs.s3_url }}
      
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
      
      - name: Create bucket in S3
        run: |
          echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
          commit_hash=`git rev-parse HEAD`
          aws s3api create-bucket --bucket ${{ env.GITHUB_REF }} --region ${{ env.AWS_REGION }}

