name: S3 Build and Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["feature/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

env:
  AWS_REGION: 'eu-west-2'

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: 'Create env file'
        run: |
          echo "${{ secrets.VS_ENV_FILE }}" > .env
      - run: |
          yarn system:build
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist/system
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Create an environment for the static hosting
    environment:
      name: ds-s3-deployment
      url: ${{ steps.aws-sync.outputs.s3_url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist/system
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 1200
      - name: Get branch name for bucket name
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=${GIT_BRANCH////-}" >> $GITHUB_ENV
      - name: Create bucket in S3
        run: |
          echo "Deploying branch ${{ env.GIT_BRANCH}} to ${{ github.event.inputs.environment }}"
          commit_hash=`git rev-parse HEAD`
          aws s3api create-bucket --bucket ${{env.GIT_BRANCH}} --create-bucket-configuration LocationConstraint=eu-west-2
      - name: Upload Artifact to s3
        run: |
          aws s3 cp ./dist/system s3://${{env.GIT_BRANCH}} --recursive

