name: s3-deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["feature/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  aws-s3-deploy:
    runs-on: ubuntu-latest

    # Create an environment for the static hosting enabled & Pulumi created S3 Bucket
    environment:
      name: ds-s3-deployment
      url: ${{ steps.aws-sync.outputs.s3_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=${GIT_BRANCH////_}" >> $GITHUB_ENV
      - name: Create bucket in S3
        uses: aitorres/aws-s3-create-bucket@v1.2.0
        with:
          bucket-name: ${{ env.GIT_BRANCH }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-2'
