name: s3-deploy

on:
  # Runs on pushes targeting the default branch
#   push:
#     branches: ["feature/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  aws-s3-deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    # Create an environment for the static hosting enabled & Pulumi created S3 Bucket
    environment:
      name: ds-s3-deployment
      url: ${{ steps.aws-sync.outputs.s3_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::522018539762:role/GitHubOIDC
          aws-region: eu-west-2
      - name: Create bucket in S3
        run: |
          aws s3 mb s3://ds-test-bucket
